import { ParkourStoryboardPanel } from './parkourTypes';

export const PARKOUR_STORYBOARD_PANELS: ParkourStoryboardPanel[] = [
  {
    panelNumber: 1,
    title: 'Sprint Initiation & Forward Drive',
    startFrame: 0,
    endFrame: 11,
    frameRangeStr: 'F00 – F11 (0.00s – 0.46s)',
    actionSummary: 'Athlete launches from standing crouch into a powerful forward sprint. Torso leans 14° into the acceleration vector; arms drive in anti-phase to cancel angular torso twist.',
    biomechanicalPhase: 'Drive Phase & Acceleration',
    keyPrinciples: [
      'Extrapolated CoM pitched forward ahead of stance foot to generate horizontal propulsion',
      'Anti-phase arm pump (R arm forward with L leg forward) cancels transverse spinal torque',
      'Ground reaction force pins stance foot strictly at Y = 755.0 with zero horizontal slip',
    ],
  },
  {
    panelNumber: 2,
    title: 'High-Cadence Sprint Stride',
    startFrame: 12,
    endFrame: 23,
    frameRangeStr: 'F12 – F23 (0.50s – 0.96s)',
    actionSummary: 'Peak sprinting speed reached at X = 560px. High knee drive (femur at 85°), heel whips up toward glute to shorten swing-leg pendulum length and reduce rotational inertia.',
    biomechanicalPhase: 'Terminal Flight & Pre-Takeoff Cadence',
    keyPrinciples: [
      'Leg pendulum moment of inertia minimized by deep knee flexion during swing phase',
      'Sinusoidal pelvic vertical oscillation ±4px synchronized with footfall frequency',
      'Pelvis counter-rotates dynamically against thoracic girdle to preserve core balance',
    ],
  },
  {
    panelNumber: 3,
    title: 'Hurdle Take-off & Leg Punch',
    startFrame: 24,
    endFrame: 29,
    frameRangeStr: 'F24 – F29 (1.00s – 1.21s)',
    actionSummary: 'Lead foot plants firmly on the ground plane, knee flexes slightly to store elastic strain energy in the patellar tendon, then extends explosively launching the athlete into the air.',
    biomechanicalPhase: 'Elastic Energy Preload & Airborne Launch',
    keyPrinciples: [
      'Ground normal force exceeds 2.5x body weight during 2-frame elastic compression',
      'Spine extends slightly as torso transitions from forward lean into launch vector',
      'Both arms sweep forward-upward to maximize vertical takeoff impulse',
    ],
  },
  {
    panelNumber: 4,
    title: 'Aerial Cat Dive Parabolic Arc',
    startFrame: 30,
    endFrame: 37,
    frameRangeStr: 'F30 – F37 (1.25s – 1.54s)',
    actionSummary: 'Airborne flight along a ballistic parabola reaching apex at Y = 590px. Legs trail in aerodynamic alignment; head tilts to spot the landing target; hands reach forward-downward.',
    biomechanicalPhase: 'Ballistic Flight & Ground Intercept Reaching',
    keyPrinciples: [
      'Center of Mass strictly follows zero-drag parabolic trajectory (Vy = V0 - g*t)',
      'Visual horizon spotting: cervical spine stabilizes cranium to judge ground intercept',
      'Analytical arm IK solves forward reach toward ground contact coordinates (X = 820, Y = 755)',
    ],
  },
  {
    panelNumber: 5,
    title: 'Hand Touchdown & Elbow Yielding',
    startFrame: 38,
    endFrame: 43,
    frameRangeStr: 'F38 – F43 (1.58s – 1.79s)',
    actionSummary: 'Hands make soft contact with the floor at Y = 755.0. Elbows immediately yield from 170° down to 110° to decelerate vertical velocity without killing forward horizontal momentum.',
    biomechanicalPhase: 'Impulse Attenuation & Roll Initiation',
    keyPrinciples: [
      'Elbow flexion compliance prolongs impact duration Δt, reducing peak force F = Δp/Δt',
      'Chin tucks tightly to sternum to protect cervical vertebrae from floor contact',
      'Spine flexes into continuous spherical C-curve to prepare smooth surface roll',
    ],
  },
  {
    panelNumber: 6,
    title: 'Diagonal Scapular Shoulder Roll',
    startFrame: 44,
    endFrame: 51,
    frameRangeStr: 'F44 – F51 (1.83s – 2.13s)',
    actionSummary: 'Torso rolls smoothly over the floor from right shoulder diagonally across thoracic spine to left hip. Legs tuck tightly into chest, reducing radius of gyration and accelerating rotation.',
    biomechanicalPhase: 'Rotational Energy Dissipation & Tight Core Tuck',
    keyPrinciples: [
      'Rotational inertia I = Σ m_i r_i² minimized by tucking knees tight against chest',
      'Root position Y maintains constant contact curvature along ground plane without floor penetration',
      'Kinetic energy is smoothly redirected from vertical drop into forward rolling translation',
    ],
  },
  {
    panelNumber: 7,
    title: 'Roll Exit & Rebound Plant',
    startFrame: 52,
    endFrame: 61,
    frameRangeStr: 'F52 – F61 (2.17s – 2.54s)',
    actionSummary: 'Athlete rolls over the pelvis and swings both feet through to plant firmly on the floor at X = 1040px. Momentum drives athlete into a deep athletic blocking crouch.',
    biomechanicalPhase: 'Horizontal Braking & Elastic Rebound Preload',
    keyPrinciples: [
      'Feet plant securely at Y = 755.0, expanding Base of Support across [1010..1060]px',
      'Deep knee compression to 105° absorbs residual forward momentum',
      'Arms sweep backward behind the torso, preloading the shoulder extensors for backflip takeoff',
    ],
  },
  {
    panelNumber: 8,
    title: 'Explosive Backflip Takeoff Punch',
    startFrame: 62,
    endFrame: 69,
    frameRangeStr: 'F62 – F69 (2.58s – 2.88s)',
    actionSummary: 'Quadriceps and calves fire explosively; arms whip forcefully upward past the ears. Torso lifts and arches backward as character launches into the air with high upward and rotational momentum.',
    biomechanicalPhase: 'Vertical Thrust & Angular Momentum Generation',
    keyPrinciples: [
      'Upward arm whip generates reactionary downward force through ground before launch',
      'Head and chest drive upward and backward, initiating backward torque τ = r × F',
      'Takeoff velocity Vy < -22px/f provides ample flight time to complete full 360° rotation',
    ],
  },
  {
    panelNumber: 9,
    title: 'Inverted Aerial Apex & 360° Tuck',
    startFrame: 70,
    endFrame: 81,
    frameRangeStr: 'F70 – F81 (2.92s – 3.38s)',
    actionSummary: 'At the apex of the jump (Y = 390px), the athlete pulls knees tight to the chest and grips shins. The body rotates 360° backwards in mid-air, passing completely upside down before opening.',
    biomechanicalPhase: 'Airborne Inversion & Angular Conservation',
    keyPrinciples: [
      'Conservation of Angular Momentum: L = I · ω = const. Smaller radius r yields high spin rate ω',
      'Character reaches full 180° inversion precisely at parabolic flight apex (F75)',
      'At 300° rotation, athlete releases tuck, extends limbs to increase inertia I and brake spin',
    ],
  },
  {
    panelNumber: 10,
    title: 'Landing Impact Cushion & Heroic Equilibrium',
    startFrame: 82,
    endFrame: 95,
    frameRangeStr: 'F82 – F95 (3.42s – 3.96s)',
    actionSummary: 'Feet touch down softly at Y = 755.0. Knees compress 45° absorbing ground reaction force; torso pitches forward to center CoM over feet; arms extend into athletic guard posture.',
    biomechanicalPhase: 'Impact Cushioning & Dynamic Balance Recovery',
    keyPrinciples: [
      'Knee flexion from 165° down to 118° cushions 32px of vertical drop over 4 frames',
      'Torso forward pitch (14°) brings Extrapolated CoM directly within the mid-foot Base of Support',
      'Final harmonic settle: muscles lock into stable athletic stance with stability margin > 28px',
    ],
  },
];
